import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import axios from 'axios';


export default function ServView() {

    const [data, setData] = useState([]);

    const [message, setMessage] = useState("");

    const router = useRouter();
    const [id] = useState(router.query.id);

    const getUser = async () => {
        if (id === undefined) {
            setMessage("Erro: usuário não encontrado!")
            return
        }

        await axios.get('http://localhost:8080/users/' + id)
            .then((Response) => {
                setData(Response.data.user);
            }).catch((err) => {
                if (err.response) {
                    setMessage(err.response.data.message);
                } else {
                    setMessage("Erro: Tente mais tarde!");
                }

            })
    }

    useEffect(() => {
        getUser();
    }, [id]);


    return (
        <>
            <Head>
                <title>Form</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <form className={`${styles.form}`}>
                    <div>
                        <Link  href={"/"}><button type='button'>List</button>{" "}</Link>
                        <Link href={"/servRegister"}><button type='button' >Register</button></Link>
                    </div>

                    <h2 className={`${styles.h2}`}>User details</h2>
                    {message ? <p>{message}</p> : ""}
                    <div className={`${styles.span}`}>
                        <span >ID: {data.id}</span><br />
                        <span >Name: {data.name}</span><br />
                        <span>E-mail: {data.email}</span><br />
                    </div>
                </form>
            </main>
        </>
    )
}
