import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import styles from '@/styles/Home.module.css';
import { servDelete } from './servDelete';

export default function List() {

  const [data, setData] = useState([]);

  const [page, setPage] = useState("");

  const [lastPage, setLastPage] = useState("");

  const [message, setMessage] = useState("");

  const getUsers = async (page) => {


    if (page === undefined) {
      page = 1;
    }

    setPage(page);

    await axios.get("http://localhost:8080/users?page=" + page)
      .then((response) => {

        setData(response.data.users);
        setLastPage(response.data.pagination.lastPage);

      }).catch((err) => {

        if (err.response) {
          setMessage(err.response.data.message);
        } else {
          setMessage("Error: Please try again later!");
        }

      });
  }

  useEffect(() => {
    getUsers();
  }, []);

  const deleteUser = async (idUser) => {
    if (window.confirm('Are you sure you want to delete?')) {
      const response = await servDelete("http://localhost:8080/users/" + idUser);
      setMessage(response);
      getUsers(page);
    }
  }

  return (
    <>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Link href={"/servRegister"}><button type='button' >Register</button></Link>
        <h2 className={`${styles.h2}`} >List users</h2>
        {message ? <p>{message}</p> : " "}

        {data.map(user => (
          <div className={`${styles.span}`} key={user.id}>
            <span>ID: {user.id} </span><br />
            <span>Name: {user.name} </span><br />
            <span>E-mail: {user.email} </span><br /> <br />
            <Link href={`/servEdit/${user.id}`}><button type='button'>Edit</button>{" "}</Link>
            <Link href={`/servView/${user.id}`}><button type='button'>View</button>{" "}</Link>
            <button type='button' onClick={() => deleteUser(user.id)}>Delete</button>{""}
            <hr />
          </div>
        ))}

        {page !== 1 ? <button type='button' onClick={() => getUsers(1)}
        >First</button> : <button type='button' disabled>First</button>}{" "}

        {page !== 1 ? <button type='button' onClick={() => getUsers(page - 1)}>{page - 1}</button> : ""}{" "}

        <button type='button' disabled>{page}</button>{" "}

        {page + 1 <= lastPage ? <button type='button' onClick={() => getUsers(page + 1)}>{page + 1}</button> : ""}{" "}

        {page !== lastPage ? <button type='button' onClick={() => getUsers(lastPage)}>
          Last</button> : <button type='button' disabled>Last</button>}{""}

        <br /> <br />
       
      </main>
    </>
  )
}
