import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import axios from 'axios';
import Link from 'next/link';


export default function servRegister() {
  
  const [data, setData] = useState({
    name: '',
    email: ''
  });

  const [message, setMessage] = useState("");

  const valueInput = (e) => setData({ ...data, [e.target.name]: e.target.value });

  const addUser = async (e) => {

    e.preventDefault();

    const headers = {
      'headers': {
        'Content-Type': 'application/json'
      }
    }

    await axios.post("http://localhost:8080/users", data, headers)
      .then((response) => {
        setMessage(response.data.message);
        setData({
          name: '',
          email: ''
        });
      }).catch((err) => {
        if (err.response) {
          setMessage(err.response.data.message);
        } else {
          setMessage("Erro: Tente novamnte mais tarde ou entre em contato com...!");
        }
      });
  }


  return (
    <>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <form onSubmit={addUser} className={`${styles.form}`}>
          <div>
          <Link  className={`${styles.list}`} href={"/"}><button type='button'>List</button>{" "}</Link>
          </div>
          
          
          <h2 className={`${styles.h2}`} >Register user</h2>
          {message ? <p>{message}</p> : ""}


          <label className={`${styles.label}`}>Name</label>
          <input className={`${styles.input}`} type='text' name='name' placeholder='Enter the name' onChange={valueInput} value={data.name} />

          <label className={`${styles.label}`}>E-mail</label>
          <input className={`${styles.input}`} type='email' name='email' placeholder='Enter the e-mail' onChange={valueInput} value={data.email} />

          <button className={`${styles.button}`} type='submit'>To save</button>
         
        </form>
      </main>
    </>
  )
}
